import 'dart:convert';
import 'dart:io';
import 'package:pdf/pdf.dart';
import 'package:pdf/widgets.dart' as pw;
import 'package:path_provider/path_provider.dart';
import 'package:share_plus/share_plus.dart';
import '../models/room_scan.dart';
import '../core/utils/measurement_utils.dart';
import 'exporters/cad_exporters.dart';

/// Production multi-format CAD & document export service.
class ExportService {
  
  /// Export room scan to specified CAD/Document file format.
  Future<String> exportToFile(RoomScan scan, String format, {bool isMetric = true}) async {
    final dir = await getApplicationDocumentsDirectory();
    final exportDir = Directory('${dir.path}/exports');
    await exportDir.create(recursive: true);

    final cleanId = scan.id.replaceAll(RegExp(r'[^\w]'), '_');

    switch (format.toLowerCase()) {
      case 'dxf':
        final path = '${exportDir.path}/${cleanId}_plan.dxf';
        await File(path).writeAsString(CadExporters.exportDxf(scan));
        return path;
      case 'svg':
        final path = '${exportDir.path}/${cleanId}_plan.svg';
        await File(path).writeAsString(CadExporters.exportSvg(scan, isMetric: isMetric));
        return path;
      case 'obj':
        final path = '${exportDir.path}/${cleanId}_mesh.obj';
        await File(path).writeAsString(CadExporters.exportObj(scan));
        return path;
      case 'glb':
      case 'json':
        return await exportJson(scan);
      case 'pdf':
      default:
        return await exportPdf(scan, isMetric: isMetric);
    }
  }

  /// Export room scan as high-resolution PDF report.
  Future<String> exportPdf(RoomScan scan, {bool isMetric = true}) async {
    final pdf = pw.Document();

    final label = scan.label ?? 'Room Scan';
    final area = scan.area ?? 0.0;
    final perimeter = scan.perimeter ?? 0.0;
    final height = scan.roomHeight ?? 2.60;

    pdf.addPage(
      pw.Page(
        pageFormat: PdfPageFormat.a4,
        build: (context) {
          return pw.Column(
            crossAxisAlignment: pw.CrossAxisAlignment.start,
            children: [
              pw.Text(label,
                  style: pw.TextStyle(
                      fontSize: 24, fontWeight: pw.FontWeight.bold)),
              pw.SizedBox(height: 8),
              pw.Text('Generated by Liddar Production 3D AR Engine',
                  style: const pw.TextStyle(fontSize: 12, color: PdfColors.grey600)),
              pw.SizedBox(height: 4),
              pw.Text('Date: ${scan.scannedAt.toString().split('.')[0]} | Height Source: ${scan.isHeightMeasured ? "Measured (True AR)" : "User Confirmed Calibration"}',
                  style: const pw.TextStyle(fontSize: 12, color: PdfColors.grey600)),
              pw.Divider(),
              pw.SizedBox(height: 16),

              // Room Summary Table
              pw.Text('Room Architecture Summary',
                  style: pw.TextStyle(
                      fontSize: 16, fontWeight: pw.FontWeight.bold)),
              pw.SizedBox(height: 8),
              pw.Table(
                border: pw.TableBorder.all(color: PdfColors.grey400),
                children: [
                  _pdfTableRow('Floor Area',
                      MeasurementUtils.formatArea(area, isMetric: isMetric)),
                  _pdfTableRow('Total Perimeter',
                      MeasurementUtils.formatLength(perimeter, isMetric: isMetric)),
                  _pdfTableRow('Ceiling Height',
                      MeasurementUtils.formatLength(height, isMetric: isMetric)),
                  _pdfTableRow('Enclosed Volume',
                      MeasurementUtils.formatVolume(area * height, isMetric: isMetric)),
                  _pdfTableRow('Wall Count', '${scan.walls.length}'),
                  _pdfTableRow('Door Openings', '${scan.doorCount}'),
                  _pdfTableRow('Window Openings', '${scan.windowCount}'),
                  _pdfTableRow('Room Category', scan.roomType.displayName),
                ],
              ),

              pw.SizedBox(height: 24),

              // Wall Details
              if (scan.walls.isNotEmpty) ...[
                pw.Text('Precision Wall Vectors & Dimensions',
                    style: pw.TextStyle(
                        fontSize: 16, fontWeight: pw.FontWeight.bold)),
                pw.SizedBox(height: 8),
                pw.Table(
                  border: pw.TableBorder.all(color: PdfColors.grey400),
                  children: [
                    pw.TableRow(
                      children: [
                        _pdfHeaderCell('Segment'),
                        _pdfHeaderCell('Length'),
                        _pdfHeaderCell('Thickness'),
                        _pdfHeaderCell('Height'),
                      ],
                    ),
                    ...scan.walls.asMap().entries.map((entry) {
                      final i = entry.key;
                      final wall = entry.value;
                      return pw.TableRow(
                        children: [
                          _pdfCell('Wall ${i + 1}'),
                          _pdfCell(MeasurementUtils.formatLength(
                              wall.length, isMetric: isMetric)),
                          _pdfCell(MeasurementUtils.formatLength(
                              wall.thickness, isMetric: isMetric)),
                          _pdfCell(MeasurementUtils.formatLength(
                              wall.height, isMetric: isMetric)),
                        ],
                      );
                    }),
                  ],
                ),
              ],
            ],
          );
        },
      ),
    );

    final dir = await getApplicationDocumentsDirectory();
    final path = '${dir.path}/exports/${scan.id}_floor_plan.pdf';
    final file = File(path);
    await file.parent.create(recursive: true);
    await file.writeAsBytes(await pdf.save());
    return path;
  }

  /// Export room scan as structured JSON.
  Future<String> exportJson(RoomScan scan) async {
    final dir = await getApplicationDocumentsDirectory();
    final path = '${dir.path}/exports/${scan.id}_data.json';
    final file = File(path);
    await file.parent.create(recursive: true);
    await file.writeAsString(
        const JsonEncoder.withIndent('  ').convert(scan.toJson()));
    return path;
  }

  /// Share an exported CAD or report file via system share sheet.
  Future<void> shareFile(String filePath) async {
    await Share.shareXFiles([XFile(filePath)]);
  }

  // ─── PDF Helpers ───

  pw.TableRow _pdfTableRow(String label, String value) {
    return pw.TableRow(
      children: [
        pw.Padding(
          padding: const pw.EdgeInsets.all(6),
          child: pw.Text(label,
              style: pw.TextStyle(fontWeight: pw.FontWeight.bold)),
        ),
        pw.Padding(
          padding: const pw.EdgeInsets.all(6),
          child: pw.Text(value),
        ),
      ],
    );
  }

  pw.Widget _pdfHeaderCell(String text) {
    return pw.Container(
      color: PdfColors.grey200,
      padding: const pw.EdgeInsets.all(6),
      child: pw.Text(text,
          style: pw.TextStyle(fontWeight: pw.FontWeight.bold)),
    );
  }

  pw.Widget _pdfCell(String text) {
    return pw.Padding(
      padding: const pw.EdgeInsets.all(6),
      child: pw.Text(text),
    );
  }
}
